### ISSUE TITLE
Producing different binaries

### ISSUE THREAD

**Issue by timjacobi** [lechimp-p/fifi#4]
We probably want a server and a CLI binary so fifi can run as daemon. What are your thoughts and how would we set this up in mix?

**Comment by lechimp-p** [comment]
Hm, interesting. Do we want to do this already? Currently i have no idea how one would accomplish that. I just thought about a simple stdin-reading and -interpreting stand alone program until now. At some point a daemon will be nice, though. Your call as UI-lead, i think.

**Comment by timjacobi** [comment]
STD in reading stand alone program works for me. We can always split it out later and that could even be an interesting exercise.
