### ISSUE TITLE
Travis build failing.

### ISSUE THREAD

**Issue by lechimp-p** [lechimp-p/fifi#8]
What is [this](https://travis-ci.org/lechimp-p/fifi/builds/200752716), why is it failing and wtf is rake?

This flags my [PR](https://github.com/lechimp-p/fifi/pull/3). The other (?) build for the PR works as expected.

**Comment by vortec** [comment]
> Could not find .travis.yml, using standard configuration.

Please merge from master.

**Comment by lechimp-p** [comment]
Oh noez, ruby is default on travis??

**Comment by lechimp-p** [comment]
Works, thx!
